server:
  port: 50051
  gateway_port: 8080
  host: localhost
  timeout: 5
  base_url: http:/localhost:50051

db:
  port: 5432
  host: db
  user: postgres
  password: postgres
  name: postgres

redis:
  host: redis
  port: 6379
  password: ""
  db: 0

